default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: db0ltspbu8fhda
  username: qmpzetwqlrxfym
  password: a6c164a70ca9e3a68bf7fcc4fb434c0e12429387f8a8e0710cca5a98c2dac062
  host: ec2-3-234-22-132.compute-1.amazonaws.com
